task:
  name: "Rom Builder"
  timeout_in: 960m  
  container:
      image: marvelmathesh/docker:rom
      cpu: 8
      memory: 32G
        
  Builder:
       - apt install sudo
       - sudo apt install wget -y
       - sudo apt install curl -y
       - wget https://raw.githubusercontent.com/Subhendu-droid/JARVIS-ROM-Builder/main/build.sh
       - bash build.sh
