task:
  name: "Rom Builder"
  timeout_in: 240m  
  container:
      image: marvelmathesh/docker:rom
      cpu: 8
      memory: 32G

  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo  "============================"
      - cd ~
      - mkdir rom
      - cd rom
      - repo init -u https://github.com/Project-Xtended/manifest.git -b xs --depth=1
      - git clone  --depth 1 https://github.com/Subhendu-droid/local_manifests -b main .repo/local_manifests
      - repo sync --force-sync --no-tags --no-clone-bundle
      - echo "============================"
      - echo "Syncing Complete!"
      - echo "============================"

  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - cd ~
      - cd rom
      - export ALLOW_MISSING_DEPENDENCIES=true
      - export BUILD_BROKEN_DUP_RULES=true
      - export USE_CCACHE=1
      - export CCACHE_EXEC=/usr/bin/ccache
      - ccache -M 50G
      - . build/envsetup.sh
      - export ALLOW_MISSING_DEPENDENCIES=true
      - export BUILD_BROKEN_MISSING_REQUIRED_MODULES=true
      - lunch octavi_selene-userdebug
      - mka bacon

  Upload_script:
      - echo "============================"
      - echo "Uploading the Build..."
      - echo "============================"
      - cd ~
      - cd rom
      - cd out/target/product/selene
      - ls -lh
      - pwd
      - chmod 777 *
      - curl --upload-file V*.zip https://transfer.sh | tee link.txt && echo " "
      - echo " "
      - echo "============================"
      - echo "Build Uploaded!"
      - echo "Please see the link Below-  "
      - echo "----------------------------"
      - cat link.txt && echo " "
      - echo "============================"
